### PR TITLE
use yarn everywhere, remove package-lock, fix xhr passthrough

### LINKED ISSUE #42: Matching http request are passing
Hi,

First of all i love the idea of the library. Great Job guys!!!. I wanted to include the the library in 
my project, but i don't want to mock every request so i set MockConfig allowXHRPassthrough and allowFetchPassthrough to true. And the problem is every request 
is passing even when there is matching route and when there is response then data-mocks
replace the response. Is that intended behaviour and can the requests be intercept when they match before sending(cause for example i want to mock and endpoint before is created)?

**To Reproduce**
Just create angular project the cli and add data-mock.
Set the allowXHRPassthrough and allowFetchPassthrough to true 
Create some scenario(example: 
{
    url: /users/,
      method: 'GET',
      response: { some: 'good response' },
      responseCode: 200
})
Make a http call to that scenario(example: ''http://localhost:3000/api/users')

### PR DESCRIPTION
**Pull request by kieran-allen**
This PR aims to resolve #42.

- We were calling `XHRMock.use(proxy)` before mocks were being defined. Fixed this by moving call to after mocks defined.

- Removed unused `node-fetch` module.
- Removed `npm run` commands in favour of `yarn`.
- Added more tests for `allowXHRPassthrough` config.

### CODE REVIEW

File: src/mocks.ts [hunk 1]
```diff
@@ -112,6 +108,10 @@ export const injectMocks = (
       }
     }
   );
+
+  if (config && config.allowXHRPassthrough) {
```
Comment (grug) [inline src/mocks.ts]: Can't wait to be able to use optional chaining for things like this soon!
